### PR TITLE
Refactor image settings

### PR DESCRIPTION
**Pull request by elcritch**
Great talk the other day! Nicoru is a fantastic idea. It's tossed around my head a few times so it's awesome to see someone working on it. 

I was browsing through the code and playing around with it. It works like a charm so far! However I noted that you spelled the repository database as "repositorys.json" which is entirely logical, but would confuse native English speakers as the correct spelling is "repositories.json". It seemed one of those things that are easy to fix early on but harder to fix later. 

It seemed also that the database path was hardcoded. There were potentially a couple of places that already mismatched with `"imagesDir"` used in one location. So, I went through most of the image proc's and modified them to use a global function and `RuntimeSettings`. It seems to work well enough, and would make it easier to do interesting things like multiple databases later. This PR is the result of that effort. 

The Nimble tests run and pass, but I haven't tried running a new image. 

P.S. I'd like the idea of being able to run non-Docker images and importing tarballs. I might play around with that a bit later...

### CODE REVIEW

**Comment by fox0430** [comment]
Thank you very much!! very helpful.

I will continue to welcome issues and PR!

**Comment by fox0430** [comment]
@elcritch 

Currently, this PR seems to be broken.
Can you fix it?

**Comment by elcritch** [comment]
I'll take a look at it.

**Comment by elcritch** [comment]
Looks like by only running the tests I missed a whole section where the `RuntimeSettings` and path handling needed to be plumbed through. 

Nicoru now compiles correctly. Still haven't tested it locally though!

**Comment by fox0430** [comment]
@elcritch 

Thank you for your contribution!

**Pull request merged**
